//	Copyright (c) 2018 Chet Simpson & The Giblet Initiative
//	
//	This file is subject to the terms and conditions defined in
//	file 'LICENSE.MD', which is part of this source code package.
//
#pragma once
#include <Protocols/YMsg/ClientConnection.h>
#include <vector>
#include <string>
#include <string_view>
#include <memory>


namespace Giblet { namespace Protocols { namespace YMsg
{

	class ProfileManager
	{
	public:

		using string_type = std::string;			//	should be a UTF8 string
		using string_view_type = std::string_view;	//	should be a UTF8 string
		using container_type = std::vector<string_type>;
		using const_iterator = container_type::const_iterator;


	public:

		explicit ProfileManager(std::shared_ptr<ClientConnection> connection);
		ProfileManager(const ProfileManager&) = delete;
		virtual ~ProfileManager() = default;

		virtual void Load(string_view_type clientId, container_type profiles);

		virtual const_iterator begin() const;
		virtual const_iterator end() const;

		virtual string_view_type GetClientId() const;
		virtual bool IsProfileId(string_view_type id) const;
		virtual bool IsClientOrProfileId(string_view_type id) const;

		//	Actions executed by the client
		virtual void Add(string_view_type profileId) = 0;
		virtual void Activate(string_view_type id) = 0;
		virtual void Deactivate(string_view_type id) = 0;


	protected:

		//	Notifications generated by the server
		virtual void OnAdded(string_view_type profileId);
		virtual void OnActivated(string_view_type profileId);
		virtual void OnDeactivated(string_view_type profileId);


	protected:

		const std::shared_ptr<ClientConnection>	connection_;
		string_type		clientId_;
		container_type	profiles_;
	};

}}}
