//	Copyright (c) 2018 Chet Simpson & The Giblet Initiative
//	
//	This file is subject to the terms and conditions defined in
//	file 'LICENSE.MD', which is part of this source code package.
//
#pragma once
#include <Protocols/YMsg/ProfileManager.h>
#include <memory>


namespace Giblet { namespace Protocols { namespace YMsg
{

	class ProfileManagementEvents
	{
	public:

		using string_type = std::string;
		using string_view_type = std::string_view;


	public:

		ProfileManagementEvents(
			std::shared_ptr<ClientConnection> connection,
			std::shared_ptr<ProfileManager> profileManager);
		ProfileManagementEvents(const ProfileManagementEvents&) = delete;
		virtual ~ProfileManagementEvents() = default;

		//	Notifications generated by the server
		virtual void OnAdded(string_view_type profileId);
		virtual void OnActivated(string_view_type profileId);
		virtual void OnDeactivated(string_view_type profileId);


	protected:

		const std::shared_ptr<ClientConnection>	connection_;
		const std::shared_ptr<ProfileManager>	profileManager_;
	};

}}}
